package com.prueba.sofka.domain.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import java.util.List;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "EstadisticaCambioCliente")
public class EstadisticaCambioCliente {

    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBHashKey(attributeName = "sofkianoId")
    private String sofkianoId;

    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;

    @DynamoDBAttribute(attributeName = "clientesIngreso")
    private List<Cliente> clientesIngreso;

    @DynamoDBAttribute(attributeName = "clientesEgreso")
    private List<Cliente> clientesEgreso;

    public EstadisticaCambioCliente(String sofkianoId, String nombre) {
        this.id = UUID.randomUUID().toString();
        this.sofkianoId = sofkianoId;
        this.nombre = nombre;
    }
}

// package com.prueba.sofka.domain.model.entity;

// import java.util.UUID;

// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
// import lombok.Data;

// import java.util.List;
// import java.util.ArrayList;
// import java.util.Map;

// @Data
// @DynamoDBTable(tableName = "EstadisticaCambioCliente")
// public class EstadisticaCambioCliente {

//     @DynamoDBAutoGeneratedKey
//     private String id;

//     @DynamoDBHashKey(attributeName = "sofkianoId")
//     private String sofkianoId;

//     @DynamoDBAttribute(attributeName = "nombre")
//     private String nombre;

//     @DynamoDBAttribute(attributeName = "clientesIngreso")
//     private List<Map<String, Object>> clientesIngreso = new ArrayList<>();

//     @DynamoDBAttribute(attributeName = "clientesEgreso")
//     private List<Map<String, Object>> clientesEgreso = new ArrayList<>();

//     public EstadisticaCambioCliente(String sofkianoId, String nombre) {
//         this.id = UUID.randomUUID().toString();
//         this.sofkianoId = sofkianoId;
//         this.nombre = nombre;
//     }

    
//     public String getSofkianoId() {
//         return sofkianoId;
//     }

//     public void setSofkianoId(String sofkianoId) {
//         this.sofkianoId = sofkianoId;
//     }

    
//     public String getNombre() {
//         return nombre;
//     }

//     public void setNombre(String nombre) {
//         this.nombre = nombre;
//     }

   
//     public List<Map<String, Object>> getClientesIngreso() {
//         return clientesIngreso;
//     }

//     public void setClientesIngreso(List<Map<String, Object>> clientesIngreso) {
//         this.clientesIngreso = clientesIngreso;
//     }

   
//     public List<Map<String, Object>> getClientesEgreso() {
//         return clientesEgreso;
//     }

//     public void setClientesEgreso(List<Map<String, Object>> clientesEgreso) {
//         this.clientesEgreso = clientesEgreso;
//     }
// }







